{{- if .Values.api.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bright.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bright.labels" . | nindent 4 }}
data:
  API_KEY: {{ required "api.apiKey must be provided" .Values.api.apiKey | b64enc | quote }}
{{- end }}