name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm_version: [3.11.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '${{ matrix.helm_version }}'

      - name: Helm version
        run: helm version -c

      - name: Run lint
        run: helm lint .
