name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm i -q --no-save @semantic-release/exec @semantic-release/git

      - name: Release a new version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login --username ${{ github.actor }} --password-stdin

      - name: Package Chart
        run: helm package .

      - name: Push charts to GHCR
        run: helm push ./sniffer-agent-*.tgz oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}
